name: Windows

on: [ push, pull_request ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: true
      matrix:
        java_version: [ 11 ]

    steps:
      - uses: actions/checkout@v4
      - name: "Set up JDK ${{ matrix.java_version }}"
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java_version }}
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3.2.0
      - name: build
        env:
          JAVA_VERSION: ${{ matrix.java_version }}
        run: ./gradlew build --no-daemon
      - name: Upload build code coverage
        uses: codecov/codecov-action@v4.2.0
        if: ${{ github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main') }}
        env:
          JAVA_VERSION: ${{ matrix.java_version }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: current_windows
          env_vars: JAVA_VERSION
          # too many timeout errors, let's not fail at the moment
          #fail_ci_if_error: true
